kind: pipeline
name: build
type: kubernetes

platform:
  os: linux

steps:
- name: build
  image: golang:1.20-alpine
  commands:
  - CGO_ENABLED=0 go build -ldflags -s .

- name: docker
  image: plugins/docker:20.10
  settings:
    repo: ghcr.io/rkojedzinszky/postfix-sasl-exporter
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror
